Added fixes in templates, jobs after testing

diff --git a/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/datamover-api/deployment-datamover-api.yaml b/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/datamover-api/deployment-datamover-api.yaml
--- a/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/datamover-api/deployment-datamover-api.yaml
+++ b/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/datamover-api/deployment-datamover-api.yaml
@@ -65,33 +65,33 @@ spec:
       imagePullSecrets:
         - name: triliovault-image-pull-secret
       initContainers:
-        # - name: wait-for-jobs
-        #   image: busybox
-        #   command:
-        #     - sh
-        #     - -c
-        #     - |
-        #       jobs=("triliovault-datamover-api-db-sync" "triliovault-datamover-api-ks-user" "triliovault-datamover-api-ks-endpoints")
-        #       while true; do
-        #         all_succeeded=true
-        #         for job in "${jobs[@]}"; do
-        #           if kubectl get job $job -o jsonpath="{.status.succeeded}" | grep -q "1"; then
-        #             echo "$job succeeded"
-        #           elif kubectl get job $job -o jsonpath="{.status.failed}" | grep -q "1"; then
-        #             echo "$job failed"
-        #             exit 1
-        #           else
-        #             echo "waiting for $job"
-        #             all_succeeded=false
-        #           fi
-        #         done
-        #         if [ "$all_succeeded" = true ]; then
-        #           exit 0
-        #         fi
-        #         sleep 5
-        #       done
+        - name: wait-for-datamover-jobs
+          image: busybox
+          command:
+            - sh
+            - -c
+            - |
+              jobs=("job-triliovault-datamover-api-db-init" "job-triliovault-datamover-api-keystone-init" "job-triliovault-datamover-api-rabbitmq-init")
+              while true; do
+                all_succeeded=true
+                for job in "${jobs[@]}"; do
+                  if kubectl get job $job -o jsonpath="{.status.succeeded}" | grep -q "1"; then
+                    echo "$job succeeded"
+                  elif kubectl get job $job -o jsonpath="{.status.failed}" | grep -q "1"; then
+                    echo "$job failed"
+                    exit 1
+                  else
+                    echo "waiting for $job"
+                    all_succeeded=false
+                  fi
+                done
+                if [ "$all_succeeded" = true ]; then
+                  exit 0
+                fi
+                sleep 5
+              done
         - name: triliovault-datamover-api-init
-          image: {{ .Values.images.triliovault_triliovault_datamover_api }}
+          image: {{ .Values.images.triliovault_datamover_api }}
           imagePullPolicy: IfNotPresent
           command:
             - /tmp/triliovault-datamover-api-init.sh
@@ -100,12 +100,18 @@ spec:
             - name: triliovault-datamover-api-bin
               mountPath: /tmp/triliovault-datamover-api-init.sh
               subPath: triliovault-datamover-api-init.sh
-              readOnly: true
+            - name: triliovault-datamover-api-bin
+              mountPath: /tmp/triliovault-cloudrc
+              subPath: triliovault-cloudrc
             - name: pod-shared-triliovault-datamover-api
               mountPath: /tmp/pod-shared-triliovault-datamover-api
+            - name: triliovault-datamover-api-etc
+              mountPath: /etc/pki/tls/certs/openstack-ca-cert.pem
+              subPath: ca-cert.pem
+              readOnly: true
       containers:
         - name: triliovault-datamover-api
-          image: {{ .Values.images.triliovault_triliovault_datamover_api }}
+          image: {{ .Values.images.triliovault_datamover_api }}
           imagePullPolicy: IfNotPresent
           securityContext:
             readOnlyRootFilesystem: false
@@ -120,7 +126,7 @@ spec:
                   - /tmp/triliovault-datamover-api.sh
                   - stop
           ports:
-            - name: triliovault-datamover-api
+            - name: dm-api
               containerPort: 8784
           readinessProbe:
             tcpSocket:
@@ -146,7 +152,6 @@ spec:
             - name: triliovault-datamover-api-bin
               mountPath: /tmp/triliovault-datamover-api.sh
               subPath: triliovault-datamover-api.sh
-              readOnly: true
             - name: pod-shared-triliovault-datamover-api
               mountPath: /tmp/pod-shared-triliovault-datamover-api
             - name: varlogtriliovaultdatamoverapi
diff --git a/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/workloadmgr/deployment-wlm-api.yaml b/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/workloadmgr/deployment-wlm-api.yaml
--- a/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/workloadmgr/deployment-wlm-api.yaml
+++ b/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/workloadmgr/deployment-wlm-api.yaml
@@ -49,6 +49,31 @@ spec:
       imagePullSecrets:
         - name: triliovault-image-pull-secret
       initContainers:
+        - name: wait-for-wlm-api-jobs
+          image: busybox
+          command:
+            - sh
+            - -c
+            - |
+              jobs=("job-triliovault-wlm-db-init" "job-triliovault-wlm-keystone-init" "job-triliovault-wlm-rabbitmq-init")
+              while true; do
+                all_succeeded=true
+                for job in "${jobs[@]}"; do
+                  if kubectl get job $job -o jsonpath="{.status.succeeded}" | grep -q "1"; then
+                    echo "$job succeeded"
+                  elif kubectl get job $job -o jsonpath="{.status.failed}" | grep -q "1"; then
+                    echo "$job failed"
+                    exit 1
+                  else
+                    echo "waiting for $job"
+                    all_succeeded=false
+                  fi
+                done
+                if [ "$all_succeeded" = true ]; then
+                  exit 0
+                fi
+                sleep 5
+              done
         - name: triliovault-wlm-api-init
           image: {{ .Values.images.triliovault_wlm_api }}
           imagePullPolicy: IfNotPresent
@@ -65,9 +90,15 @@ spec:
             - name: triliovault-wlm-bin
               mountPath: /tmp/triliovault-wlm-api-init.sh
               subPath: triliovault-wlm-init.sh
-              readOnly: true
+            - name: triliovault-wlm-bin
+              mountPath: /tmp/triliovault-cloudrc
+              subPath: triliovault-cloudrc
             - name: pod-shared-triliovault-wlm-api
               mountPath: /tmp/pod-shared-triliovault-wlm-api
+            - name: triliovault-wlm-etc
+              mountPath: /etc/pki/tls/certs/openstack-ca-cert.pem
+              subPath: ca-cert.pem
+              readOnly: true
       containers:
         - name: triliovault-wlm-api
           image: {{ .Values.images.triliovault_wlm_api }}
@@ -118,7 +149,6 @@ spec:
             - name: triliovault-wlm-bin
               mountPath: /tmp/triliovault-wlm-api.sh
               subPath: triliovault-wlm-api.sh
-              readOnly: true
             - name: pod-shared-triliovault-wlm-api
               mountPath: /tmp/pod-shared-triliovault-wlm-api            
       volumes:
diff --git a/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/workloadmgr/deployment-wlm-cron.yaml b/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/workloadmgr/deployment-wlm-cron.yaml
--- a/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/workloadmgr/deployment-wlm-cron.yaml
+++ b/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/workloadmgr/deployment-wlm-cron.yaml
@@ -48,6 +48,32 @@ spec:
       terminationGracePeriodSeconds: 30
       imagePullSecrets:
         - name: triliovault-image-pull-secret
+      initContainers:
+        - name: wait-for-wlm-cron-jobs
+          image: busybox
+          command:
+            - sh
+            - -c
+            - |
+              jobs=("job-triliovault-wlm-db-init" "job-triliovault-wlm-keystone-init" "job-triliovault-wlm-rabbitmq-init")
+              while true; do
+                all_succeeded=true
+                for job in "${jobs[@]}"; do
+                  if kubectl get job $job -o jsonpath="{.status.succeeded}" | grep -q "1"; then
+                    echo "$job succeeded"
+                  elif kubectl get job $job -o jsonpath="{.status.failed}" | grep -q "1"; then
+                    echo "$job failed"
+                    exit 1
+                  else
+                    echo "waiting for $job"
+                    all_succeeded=false
+                  fi
+                done
+                if [ "$all_succeeded" = true ]; then
+                  exit 0
+                fi
+                sleep 5
+              done
       containers:
         - name: triliovault-wlm-cron
           image: {{ .Values.images.triliovault_wlm_cron }}
@@ -98,7 +124,6 @@ spec:
             - name: triliovault-wlm-bin
               mountPath: /tmp/triliovault-wlm-cron.sh
               subPath: triliovault-wlm-cron.sh
-              readOnly: true
             - name: pod-shared-triliovault-wlm-cron
               mountPath: /tmp/pod-shared-triliovault-wlm-cron            
       volumes:
diff --git a/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/workloadmgr/deployment-wlm-workloads.yaml b/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/workloadmgr/deployment-wlm-workloads.yaml
--- a/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/workloadmgr/deployment-wlm-workloads.yaml
+++ b/redhat-director-scripts/rhosp18/helm-chart/tvo-chart/templates/workloadmgr/deployment-wlm-workloads.yaml
@@ -49,25 +49,31 @@ spec:
       imagePullSecrets:
         - name: triliovault-image-pull-secret
       initContainers:
-        - name: triliovault-wlm-workloads-init
-          image: {{ .Values.images.triliovault_wlm_workloads }}
-          imagePullPolicy: IfNotPresent
-          securityContext:
-            readOnlyRootFilesystem: false
-            runAsGroup: {{ .Values.common.nova_user_id }}
-            runAsUser: 0
+        - name: wait-for-wlm-workloads-jobs
+          image: busybox
           command:
-            - /tmp/triliovault-wlm-workloads-init.sh
-          terminationMessagePath: /var/log/termination-log
-          volumeMounts:
-            - name: varlogtriliovaultwlm
-              mountPath: /var/log/triliovault
-            - name: triliovault-wlm-bin
-              mountPath: /tmp/triliovault-wlm-workloads-init.sh
-              subPath: triliovault-wlm-init.sh
-              readOnly: true
-            - name: pod-shared-triliovault-wlm-workloads
-              mountPath: /tmp/pod-shared-triliovault-wlm-workloads
+            - sh
+            - -c
+            - |
+              jobs=("job-triliovault-wlm-db-init" "job-triliovault-wlm-keystone-init" "job-triliovault-wlm-rabbitmq-init")
+              while true; do
+                all_succeeded=true
+                for job in "${jobs[@]}"; do
+                  if kubectl get job $job -o jsonpath="{.status.succeeded}" | grep -q "1"; then
+                    echo "$job succeeded"
+                  elif kubectl get job $job -o jsonpath="{.status.failed}" | grep -q "1"; then
+                    echo "$job failed"
+                    exit 1
+                  else
+                    echo "waiting for $job"
+                    all_succeeded=false
+                  fi
+                done
+                if [ "$all_succeeded" = true ]; then
+                  exit 0
+                fi
+                sleep 5
+              done
       containers:
         - name: triliovault-wlm-workloads
           image: {{ .Values.images.triliovault_wlm_workloads }}
@@ -118,7 +124,6 @@ spec:
             - name: triliovault-wlm-bin
               mountPath: /tmp/triliovault-wlm-workloads.sh
               subPath: triliovault-wlm-workloads.sh
-              readOnly: true
             - name: pod-shared-triliovault-wlm-workloads
               mountPath: /tmp/pod-shared-triliovault-wlm-workloads            
       volumes:
